### PR TITLE
Add -OL option when programming

### PR DESCRIPTION
**Pull request by Ouss4**
The -OL option releases the device from reset after programming.

### CODE REVIEW

**Comment by crespum** [comment]
Interesting. Where did you get that option from? I've just found [this guide](http://www.knutselaar.eu/pdf/Readme+for+PK3CMD.txt) and it's not there.

**Comment by Ouss4** [comment]
I've found it in the help, (with `ipecmd -?` , I run it on windows.)
In the link you mentioned it says -L is to release the device from reset, but I use -OL with a PIC32MZ and that what works for me. I guess I heard that the web doc isn't updated.

One little side note if you allow, ipecmd generates some log files at the location where you run the cmd. Because you run it where it is installed I guess there where you have your files.
I add ipecmd to the PATH and run it from the project directory, so I have to ignore those files for git.

I've been doing something similair to you for the Harmony TCPIP library (that's how I came across your repo.) you can check it if you want https://github.com/Ouss4/Harmony-Ceedling (it's just a draft, not really organised.)

Also I need to thank you for `rake convert` and `rake program` I was looking for these.

**Comment by crespum** [comment]
I have tried `ipecmd -?`, `ipecmd ?`, `ipecmd -h`... None of these work on Linux. That's why I couldn't find that option.

The log files are generated in the directory where the command is executed from, not in the installation path. I run it from the project directory, so I also have to ignore those files. Have you managed to change this location?

I saw your project yesterday and I will take some ideas from it. You've done some nice improvements to the `.yml`. Thanks for contributing!

**Comment by Ouss4** [comment]
Sorry I haven't tried it on Linux. I use the ipecmd.exe which is an exe wrapper of the jar file for Windows.
Did you try to run the help from the jar file?

When I didn't find those files on your .ignore I thought they got generated in the installation path, and you didn't see them. I haven't look through how to change the location, I'll let you know if I find something.

Ps. Here is a [link ](http://denethor.wlu.ca/cp316/software/Readme_for_IPECMD.txt) for `ipecmd`, the one you gave was only about `pk3cmd`, but still, not fully documenting `ipecmd`.

**Pull request merged**
